version: '3.9'

services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
